// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
namespace Rider_manager
{
    public partial class Good_ride_model
    {
        /// <summary>
        /// model input class for Good_ride_model.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"col0")]
            public string? Col0 { get; set; }

            [ColumnName(@"col1")]
            public float Col1 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Good_ride_model.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"col0")]
#pragma warning disable CS8618 // Non-nullable property 'Col0' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
            public float[] Col0 { get; set; }
#pragma warning restore CS8618 // Non-nullable property 'Col0' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.

            [ColumnName(@"col1")]
            public uint Col1 { get; set; }

            [ColumnName(@"Features")]
#pragma warning disable CS8618 // Non-nullable property 'Features' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
            public float[] Features { get; set; }
#pragma warning restore CS8618 // Non-nullable property 'Features' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
#pragma warning disable CS8618 // Non-nullable property 'Score' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
            public float[] Score { get; set; }
#pragma warning restore CS8618 // Non-nullable property 'Score' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("good_ride_model.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
